# ===============================d
# MongoDB
# ===============================
spring.data.mongodb.uri=${MONGODB_URI}

# ===============================
# Server Settings
# ===============================
server.port=8080
spring.jackson.time-zone=Asia/Seoul

# ===============================
# Spotify API
# ===============================
spotify.client-id=${SPOTIFY_CLIENT_ID}
spotify.client-secret=${SPOTIFY_CLIENT_SECRET}

# ===============================
# Logging
# ===============================
logging.level.org.springframework.web=INFO
logging.level.com.rhymix=DEBUG
